lib/sky_feed/web/router.ex
defmodule SkyFeed.Web.Router do
  use SkyFeed.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SkyFeed.Web do
    pipe_through :browser # Use the default browser stack


    get "/", PageController, :index
  end

  scope "/rss", SkyFeed.Web do
    get "/commits", FeedController, :index
  end


  # Other scopes may use custom stacks.
  scope "/api", SkyFeed.Web do
    pipe_through :api

    post "/commit-feed", CommitController, :create
  end
end

lib/sky_feed/web/controllers/commit_controller.ex
defmodule SkyFeed.Web.CommitController do
  use SkyFeed.Web, :controller

  def create(conn, %{"payload" => payload}) do
    SkyFeed.Feed.Parse.parse(payload)

    send_resp(conn, :ok, "")
  end

  def show(conn, :show, id) do

  end
end

lib/sky_feed/web/controllers/fallback_controller.ex
defmodule SkyFeed.Web.FallbackController do
  @moduledoc """
  Translates controller action results into valid `Plug.Conn` responses.

  See `Phoenix.Controller.action_fallback/1` for more details.
  """
  use SkyFeed.Web, :controller

  def call(conn, {:error, %Ecto.Changeset{} = changeset}) do
    conn
    |> put_status(:unprocessable_entity)
    |> render(SkyFeed.Web.ChangesetView, "error.json", changeset: changeset)
  end

  def call(conn, {:error, :not_found}) do
    conn
    |> put_status(:not_found)
    |> render(SkyFeed.Web.ErrorView, :"404")
  end
end

lib/sky_feed/web/controllers/feed_controller.ex
defmodule SkyFeed.Web.FeedController do
  use SkyFeed.Web, :controller

  alias SkyFeed.Feed.Commit

  def index(conn, _params) do
    commits = SkyFeed.Feed.list_commits
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("index.xml", commits: commits)
  end
end

lib/sky_feed/web/controllers/page_controller.ex
defmodule SkyFeed.Web.PageController do
  use SkyFeed.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/sky_feed/web/views/changeset_view.ex
defmodule SkyFeed.Web.ChangesetView do
  use SkyFeed.Web, :view

  @doc """
  Traverses and translates changeset errors.

  See `Ecto.Changeset.traverse_errors/2` and
  `SkyFeed.Web.ErrorHelpers.translate_error/1` for more details.
  """
  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  def render("error.json", %{changeset: changeset}) do
    # When encoded, the changeset returns its errors
    # as a JSON object. So we just pass it forward.
    %{errors: translate_errors(changeset)}
  end
end

lib/sky_feed/web/views/commit_view.ex
defmodule SkyFeed.Web.CommitView do
  use SkyFeed.Web, :view
  alias SkyFeed.Web.CommitView

  def render("index.json", %{commits: commits}) do
    %{data: render_many(commits, CommitView, "commit.json")}
  end

  def render("show.json", %{commit: commit}) do
    %{data: render_one(commit, CommitView, "commit.json")}
  end

  def render("commit.json", %{commit: commit}) do
    %{id: commit.id}
  end
end

lib/sky_feed/web/views/error_view.ex
defmodule SkyFeed.Web.ErrorView do
  use SkyFeed.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/sky_feed/web/views/feed_view.ex
defmodule SkyFeed.Web.FeedView do
  use SkyFeed.Web, :view


  def date_format(commit) do
    {:ok, date } = commit.inserted_at
    |> Ecto.DateTime.to_iso8601
    |> DateFormat.parse("{ISOz}")

    {:ok, date} = DateFormat.format(date, "%a, %d %b %Y %H:%M:%S %z", :strftime)

    date
  end
end

lib/sky_feed/web/views/layout_view.ex
defmodule SkyFeed.Web.LayoutView do
  use SkyFeed.Web, :view
end

lib/sky_feed/web/views/page_view.ex
defmodule SkyFeed.Web.PageView do
  use SkyFeed.Web, :view
end

lib/sky_feed/web/templates/feed/index.html.eex
<?xml version="1.0" encoding="UTF-8"?>  
<rss version="2.0">  
  <channel>
    <title>SkyFeed</title>
    <description>LiquidSky Engineers, hard at work!</description>
    <link><%= commit_url(@conn, :index) %></link>
    <%= for commit <- @items do %>
      <item>
        <title>
          <![CDATA[<%= commit.author %>]]>
        </title>

        <link><%= commit_url(@conn, :show, commit.id) %></link>

        <description>
          <![CDATA[<%= commit.message %>]]>
        </description>

        <pubDate><%= date_format(commit)  %></pubDate>

        <guid isPermaLink="true"><%= commit_url(@conn, :show, commit.id) %></guid>

      </item>
    <% end %>
  </channel>
</rss>

lib/sky_feed/web/templates/feed/index.xml.eex
<?xml version="1.0" encoding="UTF-8"?>  
<rss version="2.0">  
  <channel>
    <title>SkyFeed</title>
    <description>LiquidSky Engineers, hard at work!</description>
    <link><%# commit_url(@conn, :index) %></link>
    <%= for commit <- @commits do %>
      <item>
        <title>
          <![CDATA[<%= commit.author %>]]>
        </title>

        <link><%# commit_url(@conn, :show, commit.id) %></link>

        <description>
          <![CDATA[<%= commit.message %>]]>
        </description>

        <pubDate><%= commit.timestamp  %></pubDate>

        <guid isPermaLink="true"><%# commit_url(@conn, :show, commit.id) %></guid>

      </item>
    <% end %>
  </channel>
</rss>

lib/sky_feed/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SkyFeed!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/sky_feed/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>